prompts: 90s anime aesthetic scene with vivid pink lighting by studio ghibli|photo-1
init_image: vapor.png
image_prompts:
size:
  - 256
  - 256
output_dir: output
input_dir: input
step_size: 0.3
display_freq: 10 # saves progress so far at multiples of this interval
max_iterations: 50
seed: # leave blank for random
prompt_frequency:
noise_prompt_weights: #list
noise_prompt_seeds: #list
init_weight:
init_noise: # None (blank), pixels, gradient
optimiser: DiffGrad # Adam, AdamW, Adagrad, Adamax, DiffGrad, AdamP, RAdam, RMSprop
# options: faceshq, vqgan_gumbel_f8_8192, wikiart_16384, vqgan_imagenet_f16_16384, vqgan_imagenet_f16_1024
# leave blank to use default model
vqgan_type:
cutn: 12 # max I've been able to use before OOM is 18
cut_pow: 1 #default 1
cut_method: nrupdated # original, updated, nrupdated, updatedpooling, latest. default=latest
default_config: vqgan_imagenet_f16_1024 # used if no config found
default_model: vqgan_imagenet_f16_16384
clip_model: ViT-B/16 # default: ViT-B/32; also ViT-B/16, RN50, RN101, RN50x4, RN50x16
weight_decay: 1e-9 # only used for DiffGrad, default 1e-9
cuda_device: cuda:0
cudnn_determinism: False
max_split_size_mb: 2048
cudnn_benchmark: True # NR: True is a bit faster, but can lead to OOM. False is more deterministic.
ignore_alpha: True #if this is an alpha cutout, don't copy over the initial image's alpha channel
realesrgan: True # upscale
realesrgan_model: x2 # x2, x4, x8. probably gonna get OOM with x8
upscale_always: True # upscale every checkpoint (not used with nine slice in generate_loop.py)
# None (blank), integer from 0 to 8, or ordinal directions as string (NW, SE, etc)
# this is only used by generate.py, generate_loop.py generates every slice
nine_type:
save_nine: False # save every slice as its own individual image
smooth: 0.5 # composite smoothstep lower bound
slice_prompts:
  - a pillar of white porcelain tiles
  - a skylight behind a pillar of white porcelain tiles
  - a skylight
  - a pillar of white porcelain tiles over water
  - a spiral staircase wrapping around a pillar of white porcelain tiles over water
  - a scene over water
  - a pillar of white porcelain tiles over water
  - a spiral staircase wrapping around a pillar of white porcelain tiles over water
  - a scene over water